/* Emits include/iswprint_table.h: a two-level bitmap of glibc iswprint()
 * under C.UTF-8 over all Unicode scalar values. 256 code points per block;
 * duplicate 32-byte blocks are deduped via an index table. Run via
 * scripts/gen-tables.sh; commit the generated header. The conformance suite
 * (vs the system wc) catches drift between this table and the runtime glibc. */
#include <locale.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wctype.h>

#define NCP 0x110000
#define BLOCK 256
#define NBLOCKS (NCP / BLOCK)
#define BBYTES (BLOCK / 8)

int main(void)
{
  if (!setlocale(LC_CTYPE, "C.UTF-8") && !setlocale(LC_CTYPE, "C.utf8")) {
    fprintf(stderr, "no C.UTF-8 locale available\n");
    return 1;
  }
  static unsigned char blocks[NBLOCKS][BBYTES];
  for (unsigned cp = 0; cp < NCP; ++cp) {
    if (cp >= 0xD800 && cp <= 0xDFFF) continue; /* surrogates: leave 0 */
    if (iswprint((wint_t)cp))
      blocks[cp / BLOCK][(cp % BLOCK) / 8] |= (unsigned char)(1u << (cp % 8));
  }
  /* Dedupe blocks. */
  static unsigned short index[NBLOCKS];
  static unsigned char uniq[NBLOCKS][BBYTES];
  unsigned nuniq = 0;
  for (unsigned b = 0; b < NBLOCKS; ++b) {
    unsigned u;
    for (u = 0; u < nuniq; ++u)
      if (memcmp(blocks[b], uniq[u], BBYTES) == 0) break;
    if (u == nuniq) memcpy(uniq[nuniq++], blocks[b], BBYTES);
    index[b] = (unsigned short)u;
  }
  printf("// GENERATED by scripts/gen-tables.sh -- do not edit.\n");
  printf("// glibc iswprint() under C.UTF-8, two-level bitmap.\n");
  printf("#pragma once\n#include \"typedef.h\"\n\n");
  printf("static const u16 kIswprintIndex[%u] = {\n", NBLOCKS);
  for (unsigned b = 0; b < NBLOCKS; ++b)
    printf("%u,%s", index[b], (b % 16 == 15) ? "\n" : "");
  printf("};\n\nstatic const u8 kIswprintBlocks[%u][%u] = {\n", nuniq, BBYTES);
  for (unsigned u = 0; u < nuniq; ++u) {
    printf("{");
    for (unsigned i = 0; i < BBYTES; ++i) printf("0x%02X,", uniq[u][i]);
    printf("},\n");
  }
  printf("};\n\n");
  printf("inline bool qwcIswprint( const u32 cp )\n{\n");
  printf("  if ( cp >= 0x110000 ) return false;\n");
  printf("  const u8* block = kIswprintBlocks[kIswprintIndex[cp >> 8]];\n");
  printf("  return ( block[( cp & 0xFF ) >> 3] >> ( cp & 7 ) ) & 1;\n}\n");
  return 0;
}
